// Per-character original prose for the Rivaldle character pages.
// Each entry has: slug, name, file (icon/profile png base name), role, hp,
// affiliation, year, species, ult, and three prose blocks.
// Author: Rivaldle team. All copy is original; written for SEO + AdSense
// content review and meant to read like a hand-written hero guide.

export const profiles = [
    {
        slug: "captain-america",
        name: "Captain America",
        file: "CaptainAmerica",
        role: "Vanguard",
        hp: 575,
        affiliation: "Avengers",
        year: 1941,
        species: "Human",
        ult: "FREEDOM CHARGE",
        abilities: ["SENTINEL STRIKE", "FREEDOM CHARGE", "LEADING DASH", "VIBRANIUM ENERGY SAW", "LIBERTY RUSH", "SUPER-SOLDIER SLAM", "LIVING LEGEND"],
        emoji: ["⭐", "🕰️", "🛡️", "🇺🇸"],
        origin: "Steve Rogers debuted in <em>Captain America Comics</em> #1 in March 1941, drawn by Jack Kirby and written by Joe Simon. The cover famously showed him punching Hitler in the face nine months before the United States entered the Second World War. He remains, structurally, the oldest character in the <em>Marvel Rivals</em> roster.",
        history: "The Captain America we play in <em>Marvel Rivals</em> is post-thaw Steve Rogers — the man who slept through twenty years of the twentieth century and woke up to the Avengers. Most of his defining stories come from Ed Brubaker's run in the 2000s (the Winter Soldier arc, his apparent assassination, his brief replacement by Bucky), and from his repeated use as a stand-in for the United States in stories that explicitly question what that means. Rivaldle's database lists Captain America as 1941 because the field tracks the character's first comic appearance, not the in-universe present.",
        rivals: "In <em>Marvel Rivals</em>, Captain America is a 575 HP Vanguard and the prototype mobility tank. He does not deal a lot of damage. He does not particularly heal himself. What he does is run faster than other Vanguards, get to flanking Strategists before his team has finished pinging, and create the kind of pressure on the back line that lets his Duelists work the front. The shield throw is the visible element of his kit; the actual reason he is good is his movement.",
        abilitiesNote: "Most of the kit revolves around the shield. Sentinel Strike and Liberty Rush are the basic attack and dash, Leading Dash is the team-wide speed boost, and Freedom Charge is the ultimate that turns the whole team into a moving wall. Vibranium Energy Saw is the new addition that gives him an answer to Strategists who refuse to peel.",
        spotting: "In Silhouette and Pixelation modes, Captain America is one of the easier reads — round shield silhouette, A-frame pose, blue-and-red palette. In Emoji Mode, the 🇺🇸 flag is essentially a tell; we use it deliberately because the alternative is making the puzzle unsolvable. In Classic Mode, his 1941 origin year is the strongest single fingerprint — only Winter Soldier shares it, and an HP-up arrow on a Winter Soldier guess (275 → 575) confirms Cap. His 575 HP is currently the lowest of any Vanguard, which makes a Vanguard role with HP-down arrows pointing into the 500s also a near-immediate read."
    },
    {
        slug: "doctor-strange",
        name: "Doctor Strange",
        file: "DoctorStrange",
        role: "Vanguard",
        hp: 675,
        affiliation: "Avengers",
        year: 1963,
        species: "Human",
        ult: "EYE OF AGAMOTTO",
        abilities: ["DAGGERS OF DENAK", "EYE OF AGAMOTTO", "CLOAK OF LEVITATION", "MAELSTROM OF MADNESS", "PENTAGRAM OF FARALLAH", "SHIELD OF THE SERAPHIM"],
        emoji: ["👁️", "📖", "✨", "🧙‍♂️"],
        origin: "Stephen Strange first appeared in <em>Strange Tales</em> #110 in 1963, written by Stan Lee and drawn by Steve Ditko. Ditko's art for the early Doctor Strange runs is the foundation for almost every Marvel mystic that came after — the floating planes, the dimensional eyes, the geometry that does not quite obey three-dimensional logic.",
        history: "Doctor Strange's most important comic runs are the Ditko originals, Roger Stern's 1980s tenure, and Jason Aaron's 2015 run that recast him as a horror protagonist. The character's central tension is the same in every era: a brilliant surgeon whose ego cost him his hands, who replaced his old life with a magical practice that demands the same precision. He is not a hero in the mold of the other Avengers — he is a professional, and the work is real.",
        rivals: "In <em>Marvel Rivals</em>, Doctor Strange is a 675 HP Vanguard who plays nothing like the other Vanguards. He hovers, he shields, and he makes the rest of the team's positioning more flexible by literally moving them. His skill ceiling is among the highest in the game because the Cloak of Levitation lets him reposition mid-fight in ways no other Vanguard can replicate. New players try to play him as a melee tank and bounce off the role; experienced players treat him as a flying area-control specialist.",
        abilitiesNote: "Daggers of Denak and Maelstrom of Madness are his core damage. Pentagram of Farallah and Shield of the Seraphim are the survivability kit. Eye of Agamotto, his ultimate, is the team-fight reset button — it removes a window of enemy decision-making and forces your team to commit a follow-up while the enemy is locked.",
        spotting: "Doctor Strange's silhouette is one of the most distinctive in the roster — the cape flaring wide, the outstretched arms, the geometric backdrop. In Emoji Mode, the eye and book pairing is a strong cue. In Classic Mode, the Vanguard role plus 675 HP plus 1963 origin year narrows the search: only Doctor Strange, Iron Man, and Magneto are 1963 Marvel debuts in the roster, and Iron Man and Magneto have very different HP values."
    },
    {
        slug: "groot",
        name: "Groot",
        file: "Groot",
        role: "Vanguard",
        hp: 850,
        affiliation: "Guardians",
        year: 1960,
        species: "Flora Colossus",
        ult: "STRANGLING PRISON",
        abilities: ["VINE STRIKE", "STRANGLING PRISON", "THORNLASH WALL", "IRONWOOD WALL", "SPORE BOMB"],
        emoji: ["🌱", "🌌", "🌳", "🪵"],
        origin: "Groot first appeared in <em>Tales to Astonish</em> #13 in 1960, three years before the modern Marvel age really started. The original Groot was a monster-of-the-month from a pre-superhero anthology — an alien tree from Planet X who came to Earth, threatened a small town, and was driven off. He stayed shelved for decades.",
        history: "The Groot we recognize today is a 2006 Keith Giffen reinvention from <em>Annihilation: Conquest</em>, where he was retooled as a Guardian of the Galaxy alongside Rocket. The James Gunn films built on the Giffen version and locked the character into the cultural form he has today: a sentient tree with limited speech, infinite regeneration, and one of the most reliable emotional payoffs in the entire Marvel catalog.",
        rivals: "Groot in <em>Marvel Rivals</em> is the single highest-HP hero in the entire game at 850 — no other character carries that much. He is the wall-builder. His kit is built around denying space — placing Ironwood Walls to bisect a room, dropping Thornlash Walls to cut off retreats, and using Strangling Prison to lock targets in place while his Duelists collapse on them. He is the single best counter to high-mobility Duelists because his walls do not care how fast you are.",
        abilitiesNote: "Vine Strike is the basic attack; Spore Bomb is his ranged pressure tool. The walls are the defining mechanic — Ironwood for hard cover, Thornlash for damage, and Strangling Prison as the ultimate lockdown. Wall placement is a learned skill, and the difference between a 30% Groot and a 60% Groot is almost entirely how well they read the map.",
        spotting: "Groot is unmistakable in Silhouette and Pixelation Modes — broad, hulking, brown with green accents. In Emoji Mode, the tree emojis are a giveaway. In Classic Mode, the Flora Colossus species cell is unique to him — if any guess returns a yellow or red on species against your Groot guess, you can rule him out immediately for every other character. His 850 HP is also unique in the database; an HP-up arrow that points above 750 essentially names him in one column."
    },
    {
        slug: "hulk",
        name: "Hulk",
        file: "Hulk",
        role: "Vanguard",
        hp: 750,
        affiliation: "Avengers",
        year: 1962,
        species: "Human",
        ult: "PUNY BANNER",
        abilities: ["GAMMA RAY GUN", "PUNY BANNER", "GAMMA GRENADE"],
        emoji: ["🧪", "💥", "💪", "💚"],
        origin: "Bruce Banner first transformed in <em>The Incredible Hulk</em> #1 in May 1962, written by Stan Lee and drawn by Jack Kirby. The first issue had him gray, not green — the printer's ink was inconsistent, and the editorial team locked in the now-iconic green by issue two.",
        history: "Sixty years of Hulk stories have produced more emotional registers for one character than almost any other Marvel hero. Peter David's 1980s and 1990s run is the gold standard for the integrated, intelligent Hulk. Greg Pak's <em>Planet Hulk</em> turned him into a science-fantasy gladiator. Al Ewing's <em>Immortal Hulk</em> (2018–2021) reinterpreted the character through cosmic horror and remains one of the most acclaimed Marvel runs of the modern era. The <em>Marvel Rivals</em> Hulk is closer to the cinematic Banner — a scientist who turns when angry, with a costume designed around his physics labs.",
        rivals: "In <em>Marvel Rivals</em>, Hulk is the only Vanguard with a transformation mechanic baked into the core kit. He starts as Bruce Banner with a Gamma Ray Gun and a comparatively fragile body. He charges his transformation, pops Hulk form, and gains the 750 HP and brawler ultimate that the role expects. The Banner-to-Hulk transition is the entire skill expression of the character — knowing when to commit, when to wait, and when to retreat to refresh the timer.",
        abilitiesNote: "Gamma Ray Gun is the Banner-form attack. Gamma Grenade is the displacement tool. Puny Banner, the ultimate, references the Hulk's most famous comic catchphrase about Loki and is the brawler-mode payoff: enormous melee throughput, area damage, and a knockback that scales with how close his target is.",
        spotting: "Hulk's silhouette is one of the most recognizable in pop culture — wide shoulders, low center of mass, fists ready. The green palette in Pixelation Mode is essentially a tell. In Classic Mode, his eye color array (Brown and Green) is unusual and helps confirm the guess; very few heroes carry two eye colors. His 1962 origin places him in the dense first-wave Marvel cluster alongside Thor and Spider-Man, so origin year alone is not enough to pin him down."
    },
    {
        slug: "thor",
        name: "Thor",
        file: "Thor",
        role: "Vanguard",
        hp: 600,
        affiliation: "Avengers",
        year: 1962,
        species: "Asgardian",
        ult: "God of Thunder",
        abilities: ["Mjolnir Bash", "Hammer Throw", "Lightning Realm", "Storm Surge", "Awakening Rune", "God of Thunder"],
        emoji: ["☁️", "👑", "⚡", "🔨"],
        origin: "Thor debuted in <em>Journey into Mystery</em> #83 in August 1962, also by Lee and Kirby. The hammer Mjolnir was an elaborate thank-you to a real hammer — Kirby modeled the design on a thick-headed mason's tool he kept in his studio. The character's medical-doctor alter ego, Donald Blake, was the original framing device, though most modern stories quietly retire it.",
        history: "Thor's most enduring period is Walt Simonson's 1983–1987 run, which redefined the visual language of Asgard and made Beta Ray Bill canon. Jason Aaron's 2012–2019 run is the modern landmark, including <em>God of Thunder</em>, the Jane Foster Thor arc, and the long buildup to the <em>War of the Realms</em> event. Aaron's version is the one most readers under 35 picture when they hear the name, and it informs the costuming and emotional weight of the Rivals model.",
        rivals: "Thor is a 600 HP Vanguard, on the lower end of the tank pool, which is a conscious design choice — he is the Vanguard who plays like a Duelist. The kit is built around the Awakening Rune resource, which charges through hammer throws and unlocks Storm Surge for empowered melee bursts. He rewards aggressive forward play. Players who try to anchor with him on a control point will find him underperforming; players who treat him as a brawling Vanguard with hammer-uppercut combos will find him excellent.",
        abilitiesNote: "Mjolnir Bash and Hammer Throw are the two-pronged attack. Lightning Realm is the area denial. Storm Surge is the empowered window. God of Thunder, the ultimate, is one of the cleanest area-clear ultimates in the game and works well to break stalemates on objective points.",
        spotting: "The horned-helmet silhouette is the giveaway in Silhouette and Pixelation Modes — only Loki, Hela, and the Thor model wear a winged or horned helm. The hammer is universal Thor iconography in Emoji Mode. In Classic Mode, his 600 HP is the second-lowest in the Vanguard role (only Captain America at 575 is lower), and his Asgardian species cell narrows the field to three; combined with the Avengers affiliation, he's resolved in two columns."
    },
    {
        slug: "magneto",
        name: "Magneto",
        file: "Magneto",
        role: "Vanguard",
        hp: 650,
        affiliation: "X-Men",
        year: 1963,
        species: "Mutant",
        ult: "METEOR M",
        abilities: ["IRON VOLLEY", "METEOR M", "METALLIC CURTAIN", "METAL BULWARK", "IRON BULWARK", "MAG-CANNON", "MAGNETIC DESCENT"],
        emoji: ["🪖", "🧲", "🌀", "🦹‍♂️"],
        origin: "Magneto first appeared in <em>X-Men</em> #1 in September 1963, created by Lee and Kirby as the original X-Men antagonist. The character was reframed in the 1980s by Chris Claremont as a Holocaust survivor whose mutant prejudice paranoia was rooted in literal historical violence, and that reframing is the load-bearing context for every Magneto story since.",
        history: "Claremont's <em>Uncanny X-Men</em> run is the foundation. The 2000s saw two major arcs that further cemented the character — Grant Morrison's <em>New X-Men</em>, which (briefly) gave him an alternate persona named Xorn, and the <em>House of M</em> event that handed him the consequences of his own ideology in concentrated form. In <em>Marvel Rivals</em> the character is presented as a Vanguard, which is unusual for him — most appearances cast him as a damage-dealing mutant, but the design team built him around field control instead.",
        rivals: "Magneto is a 650 HP Vanguard whose kit is built around metal walls and projectile parries. Iron Bulwark and Metal Bulwark are his two flavors of barrier, and the Mag-Cannon is the signature ranged tool. He is the Vanguard most hostile to projectile-heavy compositions because Metallic Curtain literally redirects metal-based attacks. Against teams with no projectiles he loses some of his identity; against gun-heavy lineups he is one of the strongest tanks in the game.",
        abilitiesNote: "Iron Volley is the spammable basic. Magnetic Descent is the gap-closer. Meteor M, the ultimate, drops a slab of magnetic mass in a target zone — the damage is high and the area denial is high, and a well-placed Meteor M ends a team fight by itself.",
        spotting: "The helmet is the Silhouette and Pixelation tell — the wide horns of the helm plus the cape make a profile no other character shares. In Emoji Mode the magnet emoji is essentially a fingerprint. In Classic Mode his Mutant species cell narrows the field to the X-Men cluster, and his 650 HP narrows it further within that cluster — very few mutants carry that much HP."
    },
    {
        slug: "peni-parker",
        name: "Peni Parker",
        file: "PeniParker",
        role: "Vanguard",
        hp: 650,
        affiliation: "Spider-Verse",
        year: 2014,
        species: "Human",
        ult: "SPIDER-SWEEPER",
        abilities: ["CYBER-WEB CLUSTER", "SPIDER-SWEEPER", "BIONIC SPIDER-NEST", "ARACHNO-MINE", "CYBER-BOND", "WALL CRAWL", "CYBER-WEB SNARE"],
        emoji: ["📓", "🤖", "🕸️", "🕷️"],
        origin: "Peni Parker debuted in <em>Edge of Spider-Verse</em> #5 in 2014, created by Gerard Way and Jake Wyatt. She is a Spider-totem from Earth-14512, a Japanese-American teenager who shares her consciousness with a radioactive spider that pilots a mech with her.",
        history: "Most readers met Peni through the 2018 film <em>Spider-Man: Into the Spider-Verse</em>, where she appears as one of the alternate-universe Spiders pulled into the central plot. The character's comic appearances since 2014 have been comparatively sparse, which is part of why her Rivals appearance feels novel — she has never had a defining solo run, only event work and Spider-Verse appearances.",
        rivals: "Peni Parker is a Vanguard whose kit is built entirely around her mech. The 650 HP is the SP//dr armor itself, not Peni; the design lets her tank like a Vanguard while playing at a comparatively soft body inside the suit. The kit is heavy on deployables — Spider-Nest, Arachno-Mine, Cyber-Web Snare — and rewards setting up a defensive perimeter rather than charging in. She is the Vanguard most likely to be picked on a defensive map and least likely on an aggressive push.",
        abilitiesNote: "Cyber-Web Cluster is the basic ranged. Wall Crawl is the mobility. Bionic Spider-Nest summons her drone swarm. Spider-Sweeper, the ultimate, is a forward push that clears webs and damages enemies caught in the line.",
        spotting: "Peni is one of the easier silhouette and pixelation reads because of the mech profile — very few Vanguards have a humanoid robot silhouette with a cockpit window. In Emoji Mode the journal/notebook 📓 is a deliberately strange choice we use to gesture at her schoolgirl framing. In Classic Mode her 2014 origin year is the most narrowing field she has — she is one of only two heroes from after 2010, sharing the bracket with Luna Snow."
    },
    {
        slug: "venom",
        name: "Venom",
        file: "Venom",
        role: "Vanguard",
        hp: 650,
        affiliation: "None",
        year: 1988,
        species: "Symbiote",
        ult: "Feast of the Abyss",
        abilities: ["Dark Predation", "Cellular Corrosion", "Symbiotic Resilience", "Frenzied Arrival", "Feast of the Abyss"],
        emoji: ["🕷️", "🦠", "👅", "🖤"],
        origin: "The Venom symbiote first bonded to Spider-Man in <em>Amazing Spider-Man</em> #252 in 1984, but the character we know as Venom — the symbiote bonded with Eddie Brock — debuted in <em>Amazing Spider-Man</em> #300 in May 1988, by David Michelinie and Todd McFarlane. McFarlane's Venom is the silhouette every adaptation reaches for: oversized, predatory, all teeth and tongue.",
        history: "Venom has shifted between villain and antihero across decades of comics. The Lethal Protector arc of the 1990s briefly turned him into a vigilante. Donny Cates' 2018 run reframed the symbiote species through a cosmic-horror lens, introducing Knull and the symbiote dragon mythology that has informed every major Venom appearance since. The <em>Marvel Rivals</em> Venom is the Eddie Brock version, designed against the McFarlane silhouette.",
        rivals: "Venom is a 650 HP Vanguard who plays as a dive tank. He is one of the few Vanguards whose primary role is to disrupt the back line rather than hold the front. Frenzied Arrival is the gap-closer; Symbiotic Resilience is the survivability button that lets him commit and disengage. He punishes teams that do not bring a peeling Vanguard or a strong CC Strategist, and he is comparatively underwhelming against compositions that can lock him down on entry.",
        abilitiesNote: "Dark Predation is the basic tendril attack. Cellular Corrosion is the area-denial DOT. Feast of the Abyss, the ultimate, is one of the most thematic ults in the game — Venom literally devours an enemy hero. It is also a high-skill ult because catching the wrong target wastes the cooldown entirely.",
        spotting: "Venom's silhouette is one of the most recognizable in the entire Marvel catalog: the oversized head, the long tongue, the clawed hands. In Pixelation Mode the black-with-white-spider-emblem palette is unmistakable. In Emoji Mode the spider plus tongue plus black heart is essentially a literal description. In Classic Mode his Symbiote species cell is unique — only Venom has it, so a green species column on a Symbiote guess is the answer."
    },
    {
        slug: "the-thing",
        name: "The Thing",
        file: "TheThing",
        role: "Vanguard",
        hp: 700,
        affiliation: "Fantastic 4",
        year: 1961,
        species: "Human",
        ult: "CLOBBERIN' TIME",
        abilities: ["ROCKY JAB", "CLOBBERIN' TIME", "STONE HAYMAKER", "YANCY STREET CHARGE", "EMBATTLED LEAP"],
        emoji: ["💪", "😊", "👊", "🪨"],
        origin: "Ben Grimm first appeared in <em>The Fantastic Four</em> #1 in November 1961, the same comic that started the modern Marvel universe. Lee and Kirby designed the character explicitly around the trope of the disfigured strongman with a soft heart — a Frankenstein's-monster archetype recast as a working-class New York pilot.",
        history: "The Thing's defining stories are mostly Fantastic Four stories — the Galactus trilogy, the Negative Zone arcs, John Byrne's 1980s run. He has had two solo series of note (one in the 1980s, one in 2006) and remains the emotional anchor of the team. The <em>Marvel Rivals</em> design leans on his Yancy Street Brooklyn-Jewish-uncle personality, which the ability names make explicit.",
        rivals: "The Thing is the second-tankiest Vanguard at 700 HP, behind only Groot at 850, and the most straightforward melee tank in the role. The kit is built around point control and chain CC. He does not have the wall-building of Groot or the mobility of Cap, but he has the highest single-target burst of the high-HP Vanguards. He is the Vanguard you pick when you want a single point won by attrition.",
        abilitiesNote: "Rocky Jab and Stone Haymaker are the two-tier melee. Yancy Street Charge is the gap-closer with attached knockback. Embattled Leap is the vertical mobility tool. Clobberin' Time, his ultimate, is named after his comic catchphrase and triggers a high-damage AoE punch.",
        spotting: "The Thing is one of the easiest silhouette reads in the roster — wide shoulders, lumpy body, low center of mass, no hair. In Pixelation Mode the orange-rock palette is unique to him. In Classic Mode the Fantastic 4 affiliation narrows him to one of four heroes (Mr. Fantastic, Human Torch, Invisible Woman, Thing), and his 700 HP plus Vanguard role pin him down immediately within that group."
    },
    {
        slug: "emma-frost",
        name: "Emma Frost",
        file: "EmmaFrost",
        role: "Vanguard",
        hp: 650,
        affiliation: "X-Men",
        year: 1980,
        species: "Mutant",
        ult: "PSIONIC SEDUCTION",
        abilities: ["TELEPATHIC PULSE", "PSIONIC SEDUCTION", "DIAMOND FORM", "PSYCHIC SPEAR", "MIND'S AEGIS"],
        emoji: ["🧠", "💋", "❄️", "💎"],
        origin: "Emma Frost debuted in <em>X-Men</em> #129 in January 1980, created by Chris Claremont and John Byrne. She first appeared as the White Queen of the Hellfire Club, a high-society telepath antagonist for Jean Grey, and stayed a villain for nearly two decades before her face turn.",
        history: "Grant Morrison's 2001 <em>New X-Men</em> ran the heel-to-face arc in real time and made Emma a permanent X-Men fixture. The Hickman X-Men line of the 2010s placed her at the center of the Quiet Council and the politics of Krakoa. Of all the X-Men in the Rivals roster, Emma is the one whose character has changed most over four decades — from White Queen to headmistress to political leader.",
        rivals: "Emma Frost is a 650 HP Vanguard whose tankiness comes from her Diamond Form rather than baseline armor. The trick of the character is the toggle: in human form she is a long-range psionic damage dealer; in Diamond form she is a melee bruiser with damage reduction. Players who treat her as one or the other underperform — players who toggle on the right beat absolutely deal with her.",
        abilitiesNote: "Telepathic Pulse is her basic ranged attack. Mind's Aegis is the team-wide telepathic shield. Psychic Spear is the ranged burst tool. Psionic Seduction, her ultimate, charms enemy heroes into briefly fighting their teammates and is one of the best fight-resolving ultimates in the game when timed against an enemy tank.",
        spotting: "Emma is one of the few characters whose silhouette can shift mid-fight (Diamond Form vs. human), which makes Pixelation Mode harder for her than for most. In Emoji Mode the diamond is the strongest cue. In Classic Mode the X-Men affiliation plus 650 HP narrows the field — only Emma and Magneto carry both — and her 1980 origin year separates her from Magneto's 1963 instantly."
    },
    {
        slug: "black-panther",
        name: "Black Panther",
        file: "BlackPanther",
        role: "Duelist",
        hp: 275,
        affiliation: "Avengers",
        year: 1966,
        species: "Human",
        ult: "BAST'S DESCENT",
        abilities: ["VIBRANIUM CLAWS", "BAST'S DESCENT", "SPIRIT REND", "SUBTLE STEP", "SPEAR TOSS"],
        emoji: ["🌍", "👑", "🐾", "🖤"],
        origin: "T'Challa first appeared in <em>Fantastic Four</em> #52 in July 1966, created by Lee and Kirby. The character predates the Black Panther Party by a few months — the names share a coincidence rather than a lineage, though Marvel briefly renamed him 'Black Leopard' in the early 1970s to avoid the political association before reverting.",
        history: "Don McGregor's 1970s <em>Jungle Action</em> run is the first defining Black Panther material. Christopher Priest's 1998 series is the modern foundation — the bureaucratic, cold, strategic king who treats every team-up as a calculated alliance. Ta-Nehisi Coates' 2016 run reframed Wakanda's politics for a contemporary audience and remains the most cited modern run.",
        rivals: "Black Panther is a 275 HP Duelist who plays as a flanking burst assassin. Subtle Step is the invisibility-style mobility tool that defines his playstyle — he commits, lands a Spirit Rend, and pulls out before the enemy team can rotate to peel. The kit is built around chaining a dive into a clean disengage, so survivability comes from movement timing rather than HP alone.",
        abilitiesNote: "Vibranium Claws are the basic melee attack. Spear Toss is the ranged poke. Spirit Rend is the burst-damage signature ability. Bast's Descent, the ultimate, is the dive payoff — he marks targets, disappears, and reappears on each marked enemy in sequence.",
        spotting: "Black Panther is one of the harder silhouette reads because the body shape is generic — humanoid, athletic, no defining limb. The clue is the cape and the predatory crouch. In Pixelation Mode the all-black palette is the strongest cue, and in Emoji Mode the world-globe (🌍) is our gesture toward Wakanda. In Classic Mode his Avengers affiliation plus Black hair plus Brown eyes narrow him quickly — pair with the 1966 origin year and he resolves in two columns."
    },
    {
        slug: "black-widow",
        name: "Black Widow",
        file: "BlackWidow",
        role: "Duelist",
        hp: 250,
        affiliation: "Avengers",
        year: 1964,
        species: "Human",
        ult: "ELECTRO-PLASMA EXPLOSION",
        abilities: ["WIDOW'S BITE BATON", "RED ROOM RIFLE", "ELECTRO-PLASMA EXPLOSION", "FLEET FOOT", "EDGE DANCER", "STRAIGHT SHOOTER"],
        emoji: ["🧣", "💋", "🕸️", "🕷️"],
        origin: "Natasha Romanoff first appeared in <em>Tales of Suspense</em> #52 in April 1964, written by Stan Lee and drawn by Don Heck. She started as an Iron Man antagonist and a Soviet spy, defected over the next several years of stories, and by the late 1960s was an established member of the Avengers.",
        history: "Most of Black Widow's defining work is in team books — she is one of the longest-running Avengers, a frequent Champions and Defenders member, and the SHIELD-era Marvel Universe's go-to spy operative. The 2016 Mark Waid and Chris Samnee series is the best modern solo material. The Rivals version is built primarily on the Scarlett Johansson film design, with a darker tactical-suit color treatment.",
        rivals: "Black Widow is a 250 HP Duelist with the longest-range hitscan in the game via her Red Room Rifle. The kit is built around poke and pressure rather than burst — she does sustained damage from the back line and threatens to clean up low-HP targets that her Vanguards have softened. She is the Duelist most rewarded by patient play; aggressive Black Widows die to dives.",
        abilitiesNote: "Widow's Bite Baton is her melee. Red Room Rifle is the long-range marksman tool. Edge Dancer is the mobility ability. Electro-Plasma Explosion, the ultimate, is a thrown grenade that bounces and detonates with high splash damage.",
        spotting: "Black Widow's silhouette is one of the more generic in the roster — slim humanoid, ponytail, no large weapon. The hair is the giveaway in Pixelation Mode, where her red ponytail against a black bodysuit is one of the most distinctive color blocks in the game. In Classic Mode her red hair is the strongest narrowing field — she is one of three heroes with red hair, and the other two (Phoenix, Mister Fantastic) have very different roles."
    },
    {
        slug: "hawkeye",
        name: "Hawkeye",
        file: "Hawkeye",
        role: "Duelist",
        hp: 275,
        affiliation: "Avengers",
        year: 1964,
        species: "Human",
        ult: "HUNTER'S SIGHT",
        abilities: ["PIERCING ARROW", "BLAST ARROW", "HUNTER'S SIGHT", "CRESCENT SLASH", "HYPERSONIC ARROW", "RONIN SLASH", "SKYWARD LEAP"],
        emoji: ["🔍", "🎯", "🏹", "🦅"],
        origin: "Clint Barton debuted in <em>Tales of Suspense</em> #57 in September 1964 — the same anthology that introduced Black Widow earlier the same year. He started as another Iron Man antagonist before joining the Avengers in <em>Avengers</em> #16 the following year.",
        history: "Hawkeye's defining solo work is the Matt Fraction and David Aja 2012 run, which redefined the character through a slice-of-life lens — the Avenger you see when he is not Avengering. The Kate Bishop arcs that followed are connected to the same continuity. The <em>Marvel Rivals</em> design pulls from the Fraction-era purple-and-black silhouette with the Ronin sword as a callback to his post-<em>Civil War</em> identity.",
        rivals: "Hawkeye is a 275 HP Duelist who carries the highest projectile skill ceiling in the game. The bow is a charge-up weapon — pulling longer increases damage and travel speed, and a fully charged Piercing Arrow one-shots most 250 HP Duelists from full. He is the Duelist most punished by missed shots and most rewarded by clean ones.",
        abilitiesNote: "Piercing Arrow and Blast Arrow are his two ranged options. Crescent Slash and Ronin Slash are his close-range fallbacks for when a Duelist closes on him. Skyward Leap is his vertical mobility. Hunter's Sight, his ultimate, briefly outlines all enemy heroes through walls and is most valuable as an information-gathering tool, not a damage tool.",
        spotting: "The bow is the silhouette tell. In Pixelation Mode the purple-and-black palette is recognizable, though it overlaps slightly with Hela. In Emoji Mode the bow-and-arrow combination is essentially literal. In Classic Mode his 275 HP narrows him significantly — the 275 HP bracket is small, and Hawkeye, Squirrel Girl, Phoenix, Mantis, Luna Snow, Winter Soldier, and Invisible Woman are the only 275 HP characters. Pair with role to narrow further."
    },
    {
        slug: "hela",
        name: "Hela",
        file: "Hela",
        role: "Duelist",
        hp: 250,
        affiliation: "Villain",
        year: 1964,
        species: "Asgardian",
        ult: "GODDESS OF DEATH",
        abilities: ["NIGHTSWORD THORN", "GODDESS OF DEATH", "ASTRAL FLOCK", "SOUL DRAINER", "PIERCING NIGHT"],
        emoji: ["⚔️", "🖤", "👑", "💀"],
        origin: "Hela first appeared in <em>Journey into Mystery</em> #102 in March 1964, created by Lee and Kirby. The character is loosely modeled on the Norse goddess Hel, with the Marvel-specific addition of being Loki's daughter in the comics (though more recent stories have rewritten the relationship multiple times).",
        history: "Hela's most prominent comic appearances are Walt Simonson's 1980s Thor run, where she serves as the principal cosmic antagonist, and the various Ragnarok-themed event arcs of the 2000s. The 2017 film <em>Thor: Ragnarok</em> reintroduced the character to a mass audience and informs the Cate Blanchett-derived design choices in <em>Marvel Rivals</em>.",
        rivals: "Hela is a 250 HP Duelist who plays as a long-range punisher. She does not have hard mobility tools — Astral Flock is her closest analog and is more of an evasion than a gap-closer. The kit is built around chaining Nightsword Thorn projectiles into the Soul Drainer secondary, with Piercing Night as a finisher. She is one of the more punishing Duelists for new players because her movement is unforgiving.",
        abilitiesNote: "Nightsword Thorn is her primary projectile. Soul Drainer is her sustain tool. Astral Flock is the evasive movement ability. Goddess of Death, her ultimate, summons her Asgardian death horde and severely buffs her teammates within range.",
        spotting: "The horned crown is the silhouette tell, paired with Loki and Thor. The all-black-and-green palette is the Pixelation Mode signature. In Classic Mode her Asgardian species narrows the field to three (Thor, Loki, Hela), her 250 HP separates her from Thor at 600 and Loki at 275, and her Villain affiliation cell pins her down — Loki is also Villain-affiliated, but Loki's gender is Fluid, which is unique to him."
    },
    {
        slug: "iron-fist",
        name: "Iron Fist",
        file: "IronFist",
        role: "Duelist",
        hp: 300,
        affiliation: "Defenders",
        year: 1974,
        species: "Human",
        ult: "LIVING CHI",
        abilities: ["JEET KUNE DO", "YAT JEE CHUNG KUEN", "LIVING CHI", "K'UN-LUN KICK", "HARMONY RECOVERY", "CRANE LEAP", "DRAGON'S DEFENSE", "WALL RUNNER"],
        emoji: ["🎭", "🐉", "👊", "🔥"],
        origin: "Danny Rand debuted in <em>Marvel Premiere</em> #15 in May 1974, created by Roy Thomas and Gil Kane. The character was Marvel's response to the kung-fu boom of the early 1970s — a Western character grafted onto a Hong Kong cinema framework, with the mystical city of K'un-Lun supplying the fantasy element.",
        history: "Iron Fist's defining modern run is the Ed Brubaker, Matt Fraction, and David Aja series <em>The Immortal Iron Fist</em> (2006), which restored the character's mythology and introduced the lineage of past Iron Fists. Most of his other appearances are Defenders team-ups or short solo arcs. The <em>Marvel Rivals</em> design leans on the green-and-yellow comic costume rather than the more drab Netflix-era version.",
        rivals: "Iron Fist is a 300 HP Duelist who plays as a melee dive bruiser. He is one of the rare Duelists with no ranged option in his kit — every ability is close-range. The trade-off is mobility: Crane Leap and Wall Runner are two of the strongest movement abilities in the role, and he can chain them to cross most maps faster than any other Duelist. He punishes back-line Strategists harder than almost any other character in the game.",
        abilitiesNote: "Jeet Kune Do and Yat Jee Chung Kuen are his two melee combos — references to real martial-arts techniques rather than invented Marvel terms. K'un-Lun Kick is his big-damage finisher. Harmony Recovery is the self-sustain. Living Chi, the ultimate, charges his fists with the mystical energy that defines the character's mythology and dramatically increases his short-window burst.",
        spotting: "The green-and-yellow color palette is the Pixelation tell — no other Duelist shares it. In Emoji Mode the dragon emoji is essentially a giveaway. In Classic Mode his Defenders affiliation is shared only with Namor, and his 300 HP plus 1974 origin year narrow him quickly within that two-character bracket."
    },
    {
        slug: "iron-man",
        name: "Iron Man",
        file: "IronMan",
        role: "Duelist",
        hp: 250,
        affiliation: "Avengers",
        year: 1963,
        species: "Human",
        ult: "INVINCIBLE PULSE CANNON",
        abilities: ["REPULSOR BLAST", "UNIBEAM", "INVINCIBLE PULSE CANNON", "HYPER-VELOCITY", "ARMOR OVERDRIVE", "MICRO-MISSILE BARRAGE"],
        emoji: ["🔧", "💡", "🤖", "🛑"],
        origin: "Tony Stark first appeared in <em>Tales of Suspense</em> #39 in March 1963, created by Stan Lee, Larry Lieber, Don Heck, and Jack Kirby. The original armor was gray rather than red-and-gold, designed by Heck on the principle that an industrialist superhero ought to look like a piece of industrial equipment.",
        history: "Iron Man's most-cited modern runs are David Michelinie's <em>Demon in a Bottle</em> arc, Warren Ellis's <em>Extremis</em> in 2005, and Matt Fraction's <em>Invincible Iron Man</em> from 2008. The character also became the cinematic anchor of the Marvel Studios universe in 2008, and the Robert Downey Jr. casting is now load-bearing on every contemporary Iron Man depiction. The <em>Marvel Rivals</em> design leans MCU red-and-gold rather than any specific comic suit.",
        rivals: "Iron Man is a 250 HP Duelist who plays as an aerial pressure tool. He flies. He spams. He drains shields and softens targets at range. He does not duel well — his survivability is among the lowest in the role, and most players who try to fight him head-on lose. The skill ceiling is in altitude management — staying high enough to be hard to hit, low enough to land Repulsor shots, and committing Hyper-Velocity at the right moment to escape a focus.",
        abilitiesNote: "Repulsor Blast is the basic ranged. Unibeam is the burst alternative. Hyper-Velocity is the boost ability. Micro-Missile Barrage is the area damage. Invincible Pulse Cannon, his ultimate, charges and fires a single high-damage line that punches through multiple enemies and rewards committed positioning.",
        spotting: "Iron Man is one of the easier silhouette and pixelation reads thanks to the suit profile and the red-and-gold palette. The 1963 origin year is shared with Doctor Strange and Magneto, but his Duelist role separates him from both. In Classic Mode his HP plus role plus affiliation plus 1963 origin narrow the field rapidly; the Avengers affiliation cell is shared with eight other heroes but the year cell is not."
    },
    {
        slug: "magik",
        name: "Magik",
        file: "Magik",
        role: "Duelist",
        hp: 250,
        affiliation: "X-Men",
        year: 1975,
        species: "Mutant",
        ult: "DARKCHILD",
        abilities: ["SOULSWORD", "DARKCHILD", "STEPPING DISCS", "UMBRAL INCURSION", "ELDRITCH WHIRL", "MAGIK SLASH", "DEMON'S RAGE"],
        emoji: ["👩", "🗡️", "🌠", "🔥"],
        origin: "Illyana Rasputin first appeared as a child in <em>Giant-Size X-Men</em> #1 in May 1975, but her Magik identity emerged in the <em>Magik (Illyana and Storm)</em> miniseries in 1983, by Chris Claremont and John Buscema. The character's central conceit — that she was abducted to the demonic Limbo dimension as a child and aged years there in subjective time — is one of Claremont's most-imitated story devices.",
        history: "Magik has had cycles of comic prominence and absence. Her death in the <em>Inferno</em> event was an early-1990s landmark; her resurrection during the early-2000s X-line and re-emergence as a New Mutants member established the modern version. The Hickman Krakoa era of the 2010s placed her on the Quiet Council. The <em>Marvel Rivals</em> design uses the armored sorceress version with the Soulsword as the central kit element.",
        rivals: "Magik is a 250 HP Duelist whose kit is built around teleportation. Stepping Discs is the defining ability — short-range portals that let her commit to dives and instantly retreat. She has the highest engagement-disengagement skill ceiling of any Duelist; players who treat her as a regular sword fighter lose, and players who treat her as a hit-and-run teleporter excel.",
        abilitiesNote: "Soulsword and Magik Slash are her core melee. Eldritch Whirl is the AoE option. Umbral Incursion is the secondary teleport ability. Darkchild, her ultimate, transforms her into the demonic version of herself with significantly increased damage and survivability for the duration.",
        spotting: "Magik is the only Marvel Rivals character whose eye color is listed as both Blue and Red — her base form is blue-eyed, the Darkchild form is red-eyed, and the Rivaldle database lists both. That dual entry is a fingerprint in Classic Mode. Her hair is similarly listed as Blonde and White. In Pixelation Mode the heavy red-and-gold armored palette stands out, and the sword silhouette is visible in Silhouette Mode."
    },
    {
        slug: "moon-knight",
        name: "Moon Knight",
        file: "MoonKnight",
        role: "Duelist",
        hp: 275,
        affiliation: "Midnight Sons",
        year: 1975,
        species: "Human",
        ult: "HAND OF KHONSHU",
        abilities: ["CRESCENT DART", "HAND OF KHONSHU", "NIGHT GLIDER", "ANCIENT ANKH", "MOONLIGHT HOOK", "RISING LEAP", "MOON BLADE", "TRIPLE ECLIPSE"],
        emoji: ["🔮", "🎭", "🏺", "🌙"],
        origin: "Marc Spector first appeared in <em>Werewolf by Night</em> #32 in August 1975, created by Doug Moench and Don Perlin. He started as a one-off mercenary antagonist before being reimagined as the avatar of the Egyptian moon god Khonshu in the late 1970s.",
        history: "Moon Knight has had more reinventions than almost any Marvel character, including five major eras: the Bill Sienkiewicz 1980s run that established his visual signature; the Charlie Huston 2006 series that emphasized the dissociative-identity-disorder angle; the Brian Wood and Warren Ellis runs of the 2010s; the Jeff Lemire <em>Moon Knight</em> series that cemented the modern psychological framing; and Jed MacKay's 2021 series. The <em>Marvel Rivals</em> design pulls primarily from the Lemire and MacKay eras.",
        rivals: "Moon Knight is a 275 HP Duelist whose kit is the most projectile-centric in the role group. Crescent Dart is a bouncing projectile — it ricochets between enemies and walls — and the entire kit rewards pre-aiming bounces rather than direct line-of-sight shots. He has one of the highest damage ceilings in the role for players who learn his geometry and one of the lowest for players who treat him as a hitscan character.",
        abilitiesNote: "Crescent Dart and Moon Blade are his two damage tools. Night Glider is the gap-closer. Rising Leap and Moonlight Hook are his vertical mobility. Hand of Khonshu, his ultimate, summons a beam of moonlight that follows a fixed path and punishes positioning rather than rewarding aim.",
        spotting: "Moon Knight's all-white costume is the strongest single Pixelation cue in the entire roster — no other Marvel hero is dressed in solid white. In Emoji Mode the moon icon is essentially literal. In Classic Mode the Midnight Sons affiliation is unique to him within this roster, so a green affiliation cell on a Moon Knight guess is the answer instantly."
    },
    {
        slug: "namor",
        name: "Namor",
        file: "Namor",
        role: "Duelist",
        hp: 250,
        affiliation: "Defenders",
        year: 1939,
        species: "Atlantean",
        ult: "HORN OF PROTEUS",
        abilities: ["TRIDENT OF NEPTUNE", "HORN OF PROTEUS", "BLESSING OF THE DEEP", "AQUATIC DOMINION", "WRATH OF THE SEVEN SEAS"],
        emoji: ["🌊", "👑", "💪", "🐠"],
        origin: "Namor McKenzie first appeared in <em>Marvel Comics</em> #1 in October 1939 — the very first Marvel publication, two years before Captain America. That makes him the oldest character in the entire Marvel publishing catalog, and the oldest in the <em>Marvel Rivals</em> roster by a significant margin. He was created by Bill Everett.",
        history: "Namor has been a hero, an antagonist, an Avenger, an Invader, an Illuminati member, and a King of Atlantis across eight decades of comics. His most important modern run is Brian Michael Bendis' Illuminati arcs and the <em>Avengers vs. X-Men</em> event, which both leaned into his political ambition and willingness to wage war. The <em>Marvel Rivals</em> design uses the classic green-trunks Atlantean royal silhouette.",
        rivals: "Namor is a 250 HP Duelist whose kit is built around summoning support — his ult literally calls a sea creature, and Aquatic Dominion summons squid pets that auto-attack nearby enemies. He plays as a zone control and pet-management character rather than a direct duelist. The skill ceiling is in pet placement; he is one of the few characters in the game whose effective DPS is mostly delivered by units he is not directly controlling.",
        abilitiesNote: "Trident of Neptune is the basic ranged. Aquatic Dominion deploys squid summons. Blessing of the Deep is the heal. Wrath of the Seven Seas is the burst-damage charge. Horn of Proteus, his ultimate, summons a leviathan that follows a path and damages everything in its line.",
        spotting: "Namor's silhouette is one of the easier reads — pointed ears, winged ankles, no shirt, green trunks. In Pixelation Mode the green-and-skin-tone palette is unusual. In Classic Mode his 1939 origin year is unique — he is the only hero in the database with a pre-1940 origin — so an HP-down arrow on origin year toward 1939 is the answer in one column."
    },
    {
        slug: "psylocke",
        name: "Psylocke",
        file: "Psylocke",
        role: "Duelist",
        hp: 250,
        affiliation: "X-Men",
        year: 1976,
        species: "Mutant",
        ult: "DANCE OF THE BUTTERFLY",
        abilities: ["PSIONIC CROSSBOW", "DANCE OF THE BUTTERFLY", "PSI-BLADE DASH", "PSYCHIC STEALTH", "WING SHURIKENS"],
        emoji: ["🗡️", "👁️‍🗨️", "🦋", "💜"],
        origin: "Betsy Braddock first appeared in <em>Captain Britain</em> #8 in December 1976, created by Chris Claremont and Herb Trimpe. She started as Captain Britain's twin sister and a supporting character in his solo book before being recast as a telepathic X-Man in the mid-1980s.",
        history: "Psylocke went through one of the most dramatic identity changes in comics history when, in the 1989 <em>Acts of Vengeance</em> event, her consciousness was placed into the body of a Japanese assassin named Kwannon. That body — and the resulting purple-haired psionic-blade visual — became the dominant Psylocke design for thirty years before recent comics restored Betsy to her original body and made Kwannon a separate character. The <em>Marvel Rivals</em> design uses the Kwannon-body purple-haired silhouette that most readers associate with the name.",
        rivals: "Psylocke is a 250 HP Duelist who plays as a melee assassin with a ranged option. Psi-Blade Dash is the gap-closer. Psychic Stealth is the disengage. Wing Shurikens are the ranged poke for when she cannot commit to a flank. She is one of the more positionally demanding Duelists; she has burst, but her windows are short.",
        abilitiesNote: "Psionic Crossbow is the ranged opener. Wing Shurikens is the secondary ranged. Psi-Blade Dash is the closer. Psychic Stealth is the escape. Dance of the Butterfly, her ultimate, is a multi-target slash that chains across enemies in range.",
        spotting: "The purple hair is the strongest single tell in the roster — only Psylocke has Purple in her hair color array. That makes the hair color cell in Classic Mode a one-guess answer for Psylocke. In Pixelation Mode the dark-purple-with-pink-highlights palette is similarly distinctive. In Emoji Mode the butterfly is a nod to her ult."
    },
    {
        slug: "scarlet-witch",
        name: "Scarlet Witch",
        file: "ScarletWitch",
        role: "Duelist",
        hp: 250,
        affiliation: "Avengers",
        year: 1964,
        species: "Mutant",
        ult: "REALITY ERASURE",
        abilities: ["CHAOS CONTROL", "REALITY ERASURE", "MYSTIC PROJECTION", "DARK SEAL", "TELEKINESIS", "CHTHONIAN BURST"],
        emoji: ["📜", "🔮", "🟥", "🧙‍♀️"],
        origin: "Wanda Maximoff first appeared in <em>X-Men</em> #4 in March 1964, alongside her brother Quicksilver, as members of Magneto's Brotherhood of Mutants. They defected to the Avengers in <em>Avengers</em> #16 the following year, beginning the character's permanent affiliation with that team.",
        history: "Wanda's defining modern stories are John Byrne's <em>West Coast Avengers</em> run, Brian Michael Bendis' <em>House of M</em> event in 2005, and Steve Orlando's recent <em>Scarlet Witch</em> series. <em>House of M</em> in particular reshaped the character's trajectory — the line 'no more mutants' and the resulting decimation of the mutant population is referenced across the rest of Marvel publishing for a decade afterward. The <em>Marvel Rivals</em> design uses the red-and-black Olivier Coipel silhouette.",
        rivals: "Scarlet Witch is a 250 HP Duelist who plays as a sustained-AOE caster. Chthonian Burst is the basic AOE damage tool. Mystic Projection is the long-range option. The kit rewards positioning over a sightline rather than direct dueling — she is the Duelist most likely to win a fight by being unkillable for long enough rather than by burst damage.",
        abilitiesNote: "Chaos Control is the basic. Mystic Projection is her ranged. Telekinesis is her crowd-control tool. Dark Seal is the lockdown. Reality Erasure, her ultimate, channels her chaos magic into a sustained area-denial effect that wipes a control point if uncontested.",
        spotting: "Scarlet Witch's auburn hair is unique in the database — only her hair color cell shows 'Auburn,' which is distinct from Red (Black Widow, Phoenix) and Brown (Iron Man, others). That single field is a fingerprint in Classic Mode. In Pixelation Mode the red-and-pink palette stands out. In Emoji Mode the witch hat icon is the strongest cue."
    },
    {
        slug: "spider-man",
        name: "Spider-Man",
        file: "SpiderMan",
        role: "Duelist",
        hp: 250,
        affiliation: "Spider-Verse",
        year: 1962,
        species: "Human",
        ult: "Spectacular Spin",
        abilities: ["Spider-Power", "Cyber-Web Cluster", "Thwip and Flip", "Wall Crawl", "Web-Swing", "Amazing Combo", "Get Over Here!", "Spectacular Spin"],
        emoji: ["🧪", "🏙️", "🕸️", "🕷️"],
        origin: "Peter Parker first appeared in <em>Amazing Fantasy</em> #15 in August 1962, created by Stan Lee and Steve Ditko. The character was almost not published — Lee's editor Martin Goodman thought spiders were too off-putting for a hero — and the original run was an experiment that became the bestselling Marvel title for decades.",
        history: "Spider-Man's defining runs are too numerous to list compactly. The Stan Lee and Ditko years built the foundation. Roger Stern's 1980s run is the modern reference point. Brian Michael Bendis' <em>Ultimate Spider-Man</em> reframed the character for a new generation. Dan Slott's 2000s and 2010s tenure introduced the <em>Spider-Verse</em> concept that Rivals leans on for affiliation. The Rivals model uses a classic blue-and-red Peter Parker.",
        rivals: "Spider-Man is a 250 HP Duelist with the highest mobility in the role. Web-Swing and Wall Crawl let him cover ground faster than anyone else, and his combo damage is built around chaining web pulls into melee burst. The skill ceiling is in chaining mobility — players who swing only between fights underperform; players who swing during fights and hit Get Over Here! pulls on enemy back-line targets dominate.",
        abilitiesNote: "Spider-Power is the basic. Cyber-Web Cluster is the AoE option. Thwip and Flip is the close-range disengage. Get Over Here! pulls a target toward him for a melee setup. Spectacular Spin, his ultimate, is a movement-tied AOE that rewards dive timing.",
        spotting: "Spider-Man is unmistakable in every visual mode — red and blue palette, web pattern, the spider emblem. In Classic Mode his Hazel eye color is unique to him and Star-Lord, and the Spider-Verse affiliation narrows the answer to two heroes (Spider-Man and Peni Parker). His 1962 origin separates him from Peni's 2014 immediately."
    },
    {
        slug: "squirrel-girl",
        name: "Squirrel Girl",
        file: "SquirrelGirl",
        role: "Duelist",
        hp: 275,
        affiliation: "None",
        year: 1992,
        species: "Human",
        ult: "Unbeatable Squirrel Tsunami",
        abilities: ["Burst Acorn", "Squirrel Blockade", "Tail Bounce", "Mammal Bond", "Unbeatable Squirrel Tsunami"],
        emoji: ["🍂", "😂", "💪", "🐿️"],
        origin: "Doreen Green debuted in <em>Marvel Super-Heroes</em> #8 in January 1992, created by Will Murray and Steve Ditko. She was conceived as a one-off comedy character — a teenage girl with the proportional strength of a squirrel — and was intended as a cameo until Ryan North's 2015 series turned her into a Marvel mainstay.",
        history: "Ryan North and Erica Henderson's <em>The Unbeatable Squirrel Girl</em> (2015–2019) is the entire modern foundation for the character. The book is responsible for the running gag that Squirrel Girl has, in-canon, defeated Doctor Doom, Galactus, Thanos, and Kraven — typically by talking to them. The <em>Marvel Rivals</em> design uses Henderson's redesigned costume and the squirrel-summoning mechanic from the comic.",
        rivals: "Squirrel Girl is a 275 HP Duelist whose kit is built around squirrel summons and bouncing projectiles. Burst Acorn is her primary attack — a thrown projectile that explodes on impact. Squirrel Blockade summons a wall of squirrels that physically blocks enemy movement. She has one of the most thematic kits in the game; almost every ability references squirrels in some form.",
        abilitiesNote: "Burst Acorn is the basic ranged. Squirrel Blockade is the area denial. Tail Bounce is the mobility. Mammal Bond is the squirrel companion utility. Unbeatable Squirrel Tsunami, her ultimate, summons a wave of squirrels that overwhelm everything in a target area — the most literal title-drop ult in the game.",
        spotting: "Squirrel Girl is one of the few Marvel Rivals characters with Ginger hair color in the Classic Mode database, which is a fingerprint cell. The squirrel emoji in Emoji Mode is a tell. Her None affiliation is shared with Punisher and Venom, but her 275 HP plus 1992 origin year separate her from both."
    },
    {
        slug: "star-lord",
        name: "Star-Lord",
        file: "StarLord",
        role: "Duelist",
        hp: 250,
        affiliation: "Guardians",
        year: 1976,
        species: "Human",
        ult: "Galactic Legend",
        abilities: ["Element Guns", "Stellar Shift", "Blaster Barrage", "Rocket Propulsion", "Galactic Legend"],
        emoji: ["🎶", "🔫", "🌌", "😎"],
        origin: "Peter Quill first appeared in <em>Marvel Preview</em> #4 in January 1976, created by Steve Englehart and Steve Gan. The character was a comparatively obscure cosmic-Marvel figure for thirty years before Dan Abnett and Andy Lanning's <em>Annihilation</em> arcs in the 2000s placed him at the center of a reorganized Guardians of the Galaxy team.",
        history: "Star-Lord's modern profile is almost entirely built on Abnett-Lanning's 2008 Guardians run and the 2014 James Gunn film. The character became a Hollywood property before he was a comics property in any meaningful contemporary sense. The Rivals version uses the cinematic red-coat-and-helmet design.",
        rivals: "Star-Lord is a 250 HP Duelist whose kit is built around twin-pistol pressure. Element Guns are the dual-wielded primary attack. Rocket Propulsion is the boost-mobility tool — he hovers and dashes in short bursts rather than flying like Iron Man. The skill ceiling is in pistol micro-management; the guns reload independently and reward target-switching across cooldowns.",
        abilitiesNote: "Element Guns are the dual primary. Stellar Shift is the dodge. Blaster Barrage is the AOE option. Rocket Propulsion is the mobility. Galactic Legend, his ultimate, is a long-range twin-pistol burst that auto-targets nearby enemies in a wide arc.",
        spotting: "Star-Lord's Hazel eye color is shared only with Spider-Man, which makes that field a strong narrowing column in Classic Mode. The red-and-blue helmet is the Pixelation tell. In Emoji Mode the music note is a deliberate nod to the films' use of mixtapes — the cue lands harder for film viewers than for comic readers."
    },
    {
        slug: "storm",
        name: "Storm",
        file: "Storm",
        role: "Duelist",
        hp: 250,
        affiliation: "X-Men",
        year: 1975,
        species: "Mutant",
        ult: "Omega Hurricane",
        abilities: ["Wind Blade", "Bolt Rush", "Goddess Boost", "Weather Control", "Omega Hurricane"],
        emoji: ["🌧️", "☁️", "⚡", "🌪️"],
        origin: "Ororo Munroe first appeared in <em>Giant-Size X-Men</em> #1 in May 1975, created by Len Wein and Dave Cockrum. She was the most politically and culturally novel addition to the new X-Men team — a Black woman from Kenya, raised partly in Cairo, with weather-control mutations.",
        history: "Storm's defining stories are Chris Claremont's long X-Men run, where she served as team leader for most of the 1980s, and the Brian Vaughan <em>Black Panther</em> wedding arc in 2006. The character is one of Marvel's most-published characters and has been a member of X-Men, the Fantastic Four (briefly, post-marriage), and the Avengers.",
        rivals: "Storm is a 250 HP Duelist who plays as a flying area-control caster. Weather Control is the team-wide buff. Bolt Rush is the burst tool. The skill ceiling is in altitude management — she is among the most punished by Iron Man's pressure (since they fight at similar altitudes) and among the strongest at out-positioning ground-locked Duelists.",
        abilitiesNote: "Wind Blade is the basic. Bolt Rush is the burst attack. Goddess Boost is the team utility — speed and damage for nearby allies. Weather Control is the kit's centerpiece passive. Omega Hurricane, her ultimate, conjures a moving cyclone that pulls enemies in and damages them throughout the duration.",
        spotting: "Storm's white hair is shared with only Magneto and Magik (Magik via her dual entry). Storm's species cell is Mutant rather than Magneto's Mutant — wait, both are Mutant. Combine the white hair with her 250 HP and you have her: Magneto is 650 HP. In Pixelation Mode the white hair against a black-and-yellow costume is the strongest single visual cue."
    },
    {
        slug: "punisher",
        name: "The Punisher",
        file: "ThePunisher",
        role: "Duelist",
        hp: 300,
        affiliation: "None",
        year: 1974,
        species: "Human",
        ult: "Final Judgement",
        abilities: ["Adjudication", "Deliverance", "Scourge Grenade", "Culling Turret", "Vantage Connection", "Final Judgement", "Warrior's Gaze"],
        emoji: ["⚖️", "💀", "🔫", "🏴‍☠️"],
        origin: "Frank Castle first appeared in <em>The Amazing Spider-Man</em> #129 in February 1974, created by Gerry Conway and Ross Andru. He was originally a one-off antagonist, a Vietnam veteran turned vigilante who had been hired to kill Spider-Man under false pretenses. The skull-emblazoned design and the lethal-vigilante framing took hold over the next decade of appearances.",
        history: "The Punisher's most-cited modern runs are Garth Ennis' MAX-imprint series of the 2000s, which deliberately stripped the character of any superheroic context and reframed him as a war-crime drama protagonist. His relationship with the rest of Marvel publishing has always been awkward — Marvel has, at various times, asked Ennis to make him less explicitly nihilistic and asked other writers to lean into the antihero framing — and the Rivals design avoids the political controversy by leaning on his comic skull-and-tactical-vest silhouette.",
        rivals: "The Punisher is a 300 HP Duelist whose kit is built around a deployable turret and grenade pressure. Culling Turret is the deployable — placed on a sightline, it adds passive damage to wherever he is shooting. Scourge Grenade is the area denial. The kit rewards setup play more than reactive dueling. He is one of the most dangerous Duelists on a held position and one of the weakest on an open push.",
        abilitiesNote: "Adjudication and Deliverance are his ranged primaries. Scourge Grenade is the AoE. Culling Turret is the deployable. Vantage Connection is the mobility-and-positioning tool. Warrior's Gaze and Final Judgement are the ultimates — Final Judgement is the executable damage-window kill button.",
        spotting: "The skull emblem against the black tactical-vest costume is the strongest visual cue across Pixelation, Silhouette, and Emoji Modes. In Classic Mode his None affiliation narrows him to three heroes (Punisher, Squirrel Girl, Venom), and his 300 HP plus 1974 origin year pin him down — the other two have very different origin years."
    },
    {
        slug: "winter-soldier",
        name: "Winter Soldier",
        file: "WinterSoldier",
        role: "Duelist",
        hp: 275,
        affiliation: "Avengers",
        year: 1941,
        species: "Human",
        ult: "Kraken Impact",
        abilities: ["Roterstern", "Bionic Hook", "Tainted Voltage", "Trooper's Fist", "Ceaseless Charge", "Kraken Impact", "Infinite Grit"],
        emoji: ["❄️", "🔧", "🦾", "🧑‍🎤"],
        origin: "Bucky Barnes' Winter Soldier identity was retroactively introduced in Ed Brubaker's <em>Captain America</em> #1 (vol. 5) in 2005, but the original Bucky character debuted in <em>Captain America Comics</em> #1 in 1941, alongside Steve Rogers. That is why his Rivaldle origin year is 1941 rather than 2005 — the field tracks the character's first comic appearance, and Bucky is just as old as Cap.",
        history: "Brubaker's <em>Captain America</em> run is one of the most acclaimed Marvel runs of the modern era, and the Winter Soldier reveal is its central moment. The character has since been a Captain America in his own right (during Steve's death arc), an Avenger, and a frequent espionage-genre lead. The Sebastian Stan film performances inform the cinematic-coded Rivals design.",
        rivals: "Winter Soldier is a 275 HP Duelist whose kit is built around mid-range pressure and the bionic arm. Bionic Hook is the gap-closer. Roterstern (German for 'red star') is the burst tool. Trooper's Fist is the close-range melee. The kit rewards mixing ranges; he is the Duelist most punished by committing to a single distance and most rewarded by switching mid-fight.",
        abilitiesNote: "Roterstern is the burst rifle. Bionic Hook is the pull-in. Tainted Voltage is the AoE. Trooper's Fist is the melee. Ceaseless Charge is the mobility. Kraken Impact, the ultimate, is a powered-arm slam that knocks back and damages an area. Infinite Grit is the ult variant that rewards committed positioning.",
        spotting: "The 1941 origin year is shared only with Captain America in this database — that single field, with an HP-down arrow, distinguishes Winter Soldier (275 HP) from Captain America (675 HP) instantly. The bionic arm is the silhouette tell. In Pixelation Mode the gray-and-blue palette is recognizable."
    },
    {
        slug: "wolverine",
        name: "Wolverine",
        file: "Wolverine",
        role: "Duelist",
        hp: 350,
        affiliation: "X-Men",
        year: 1974,
        species: "Mutant",
        ult: "Last Stand",
        abilities: ["Savage Claw", "Feral Leap", "Undying Animal", "Vicious Rampage", "Regenerative Healing Factor", "Berserker Rage", "Last Stand"],
        emoji: ["🐺", "⚔️", "🛡️", "🦾"],
        origin: "Logan first appeared in <em>The Incredible Hulk</em> #180 in October 1974, created by Roy Thomas, Len Wein, and John Romita Sr. He was originally a Hulk antagonist for the Canadian government before being recruited into the new X-Men team in <em>Giant-Size X-Men</em> #1 the following year.",
        history: "Wolverine has had more solo titles, miniseries, and team appearances than any other X-Man. The defining runs are Chris Claremont's <em>Uncanny X-Men</em> tenure, the Frank Miller four-issue limited series in 1982, the Mark Millar <em>Old Man Logan</em> arc in 2008, and Jason Aaron's various Wolverine series across the 2000s and 2010s. The Rivals design uses the classic yellow-and-blue costume.",
        rivals: "Wolverine is one of the highest-HP Duelists in the game at 350 — a deliberate exception to the role's typical 250–275 bracket, and second only to Mister Fantastic at 375 in the role. The kit is built around regeneration, sustained damage, and Berserker Rage windows that empower his close-range output. He is the Duelist most likely to win a 1v1 in the role group and least mobile in it; he commits to fights and trusts his sustain to carry him through.",
        abilitiesNote: "Savage Claw and Vicious Rampage are his core damage. Feral Leap is the gap-closer. Undying Animal is his survivability button. Regenerative Healing Factor is the passive that defines him. Berserker Rage is the empowered window. Last Stand, the ultimate, is the desperation move — he commits to a high-damage burst window.",
        spotting: "Wolverine's 350 HP is unique in the database — Mister Fantastic at 375 is the closest neighbor, and no one else carries 350 exactly. That single HP cell is one of the strongest narrowing fields in the entire database. The yellow-and-blue costume is the Pixelation tell. In Emoji Mode the wolf icon is a deliberate misdirect — Wolverine is a mutant, not a wolf, but the silhouette association is the obvious mental shortcut."
    },
    {
        slug: "mister-fantastic",
        name: "Mister Fantastic",
        file: "MisterFantastic",
        role: "Duelist",
        hp: 375,
        affiliation: "Fantastic 4",
        year: 1961,
        species: "Human",
        ult: "BRAINIAC BOUNCE",
        abilities: ["STRETCH PUNCH", "BRAINIAC BOUNCE", "REFLEXIVE RUBBER", "FLEXIBLE ELONGATION", "DISTENDED GRIP", "ELASTIC STRENGTH"],
        emoji: ["🧑‍🔬", "🔵", "🧠", "🔬"],
        origin: "Reed Richards first appeared in <em>The Fantastic Four</em> #1 in November 1961, created by Stan Lee and Jack Kirby. The original Fantastic Four was Marvel's response to DC's Justice League and the comic that started the modern Marvel age — its bestselling success funded the early Spider-Man, Hulk, and X-Men launches.",
        history: "The Fantastic Four runs that define Reed Richards are the Lee-Kirby originals, John Byrne's 1980s tenure, Mark Waid and Mike Wieringo's 2000s run, and Jonathan Hickman's 2010 reboot. Hickman's run in particular reframes Reed as the most alarming superhero in Marvel — a man whose intelligence makes him morally unreliable — and the design through-line in the <em>Marvel Rivals</em> kit reflects the calculating-genius framing.",
        rivals: "Mister Fantastic is a 375 HP Duelist who plays as a stretchy bruiser. The kit is built around elongation — Stretch Punch is the basic, Distended Grip is the pull-in, Flexible Elongation is the long-range alternative. He has the highest HP of any Duelist in the role group, but his playstyle is much more positional than the high-HP framing suggests. He fights at medium range and rewards players who manage cooldowns rather than reflexes.",
        abilitiesNote: "Stretch Punch is the basic melee. Distended Grip pulls a target toward him. Flexible Elongation is the range extension. Reflexive Rubber is the damage absorption tool. Elastic Strength is the empowered burst. Brainiac Bounce, his ultimate, references the bouncing-rubber-body concept and is a high-mobility AoE move.",
        spotting: "Mister Fantastic's gray-streaked Brown hair is unique in the database (only Doctor Strange shares the Brown-Grey array). His Fantastic 4 affiliation narrows him to four heroes, and his 375 HP — the highest in the entire Duelist role — pins him down within that group instantly. In Pixelation Mode the blue-and-white costume is a tell, though it is similar to Invisible Woman's palette."
    },
    {
        slug: "human-torch",
        name: "Human Torch",
        file: "HumanTorch",
        role: "Duelist",
        hp: 250,
        affiliation: "Fantastic 4",
        year: 1939,
        species: "Human",
        ult: "SUPERNOVA",
        abilities: ["FIRE CLUSTER", "BLAZING BLAST", "PYRO-PRISON", "PLASMA BODY", "FLAMING METEOR", "SUPERNOVA"],
        emoji: ["💥", "💫", "💙", "🔥"],
        origin: "The Johnny Storm Human Torch first appeared in <em>The Fantastic Four</em> #1 in November 1961, but the Human Torch identity itself dates back to <em>Marvel Comics</em> #1 in October 1939 — an android Human Torch named Jim Hammond who predates the modern Marvel universe. The Rivaldle database tracks the 1939 first-appearance year because the field follows the codename, not the specific character.",
        history: "Johnny Storm has been a Fantastic Four member, a brief Avenger during one of the team's many roster shuffles, and a frequent guest in Spider-Man stories where his friendship with Peter Parker is one of the longest-running supporting-cast relationships in Marvel publishing. The Rivals design uses the classic blue-and-flame costume.",
        rivals: "Human Torch is a 250 HP Duelist who plays as a flying area-control attacker. He is one of three flying characters in the Duelist role group (along with Iron Man and Storm), and his kit overlaps mechanically with both. The distinguishing feature is the Pyro-Prison ability, which surrounds a target zone with flames and creates the only AOE-DOT-with-physical-barrier in the role group.",
        abilitiesNote: "Fire Cluster is the basic projectile. Blazing Blast is the burst. Pyro-Prison is the area-control. Plasma Body is the survivability tool. Flaming Meteor is his alternate burst attack. Supernova, the ultimate, is a self-centered AoE that demands committed positioning — too far from enemies and the damage misses, too close and he dies.",
        spotting: "The 1939 origin year is shared only with Namor in the roster. The Fantastic 4 affiliation narrows him to four; combine origin year and affiliation and the answer is unambiguous. In Pixelation Mode the orange-and-yellow flame palette is unique. In Emoji Mode the fire icon is essentially a tell."
    },
    {
        slug: "phoenix",
        name: "Phoenix",
        file: "Phoenix",
        role: "Duelist",
        hp: 275,
        affiliation: "X-Men",
        year: 1963,
        species: "Mutant",
        ult: "ENDSONG INFERNO",
        abilities: ["COSMIC FLAMES", "ENDSONG INFERNO", "TELEPATHIC ILLUSION", "DARK ASCENT", "TELEKINESIS BURST", "MIND'S GRACE"],
        emoji: ["🔥", "🦜", "🔮", "🌌"],
        origin: "Jean Grey first appeared as Marvel Girl in <em>X-Men</em> #1 in September 1963, created by Stan Lee and Jack Kirby. The Phoenix Force narrative began in 1976 with the <em>X-Men</em> #101 reveal of her cosmic upgrade, and the Dark Phoenix Saga in 1980 (Claremont and Byrne) is one of the most-cited X-Men arcs of all time.",
        history: "The Phoenix mythology is the load-bearing element of nearly every modern X-Men event. Grant Morrison's <em>New X-Men</em>, Matt Fraction's <em>Avengers vs. X-Men</em>, and Jonathan Hickman's Krakoa-era runs all build on the Dark Phoenix arc. The Rivals design uses the white-and-gold Phoenix costume rather than the classic green-and-yellow.",
        rivals: "Phoenix is a 275 HP Duelist whose kit is built around the Phoenix Force as a charge mechanic. Cosmic Flames is the basic projectile. Telekinesis Burst is the area damage. Dark Ascent is the mobility tool. The kit rewards a slow charge of the Phoenix Force resource into a committed Endsong Inferno window. New players treat her abilities as independent; experienced players treat the entire kit as a setup for the ult.",
        abilitiesNote: "Cosmic Flames is the basic. Telepathic Illusion is the CC. Telekinesis Burst is the AOE. Dark Ascent is the dash. Mind's Grace is the survivability tool. Endsong Inferno, her ultimate, is a self-centered cosmic explosion that does enormous damage in a wide area.",
        spotting: "Phoenix's red hair, green eyes, and 275 HP combine to form one of the most narrowing fingerprints in the database. The 1963 origin year places her alongside Iron Man and Doctor Strange and Magneto, but the X-Men affiliation removes them from contention. In Emoji Mode the bird (🦜) is the strongest cue."
    },
    {
        slug: "adam-warlock",
        name: "Adam Warlock",
        file: "AdamWarlock",
        role: "Strategist",
        hp: 250,
        affiliation: "Guardians",
        year: 1967,
        species: "Sovereign",
        ult: "KARMIC REVIVAL",
        abilities: ["QUANTUM MAGIC", "KARMIC REVIVAL", "SOUL BOND", "AVATAR LIFE STREAM", "COSMIC CLUSTER"],
        emoji: ["🪞", "✨", "🌌", "👑"],
        origin: "Adam Warlock first appeared (as 'Him') in <em>Fantastic Four</em> #66 in 1967, created by Stan Lee and Jack Kirby. The Adam Warlock identity took form in <em>Marvel Premiere</em> #1 in 1972 under Roy Thomas and Gil Kane, and Jim Starlin's mid-1970s run cemented the character as Marvel's central cosmic philosophical protagonist.",
        history: "Starlin's Adam Warlock runs of the 1970s, 1990s, and 2000s are the foundation. The Infinity Gauntlet, Infinity War, and Infinity Crusade events are all Starlin and Warlock-driven, and they are the source material for the cinematic Marvel Universe's Thanos arc. The Rivals design uses the classic gold-skinned silhouette with the red cape.",
        rivals: "Adam Warlock is a 250 HP Strategist whose kit is built around team revival. Karmic Revival, the ultimate, instantly resurrects fallen teammates in range — one of the most game-deciding ultimates in the role group. Soul Bond links his health to a teammate, sharing damage. The skill ceiling is in linkage management and ult timing; a wasted Karmic Revival often loses the round.",
        abilitiesNote: "Quantum Magic is his basic ranged damage. Cosmic Cluster is the AoE alternative. Avatar Life Stream is the heal. Soul Bond is the linked-life utility. Karmic Revival, the ultimate, is the team-wide resurrection.",
        spotting: "Adam Warlock's species cell is Sovereign, which is unique to him in the database. That single field is a one-guess answer in Classic Mode. His gold hair and white eyes are also unique combinations. In Emoji Mode the mirror icon is our nod to his Soul Gem-as-mirror imagery from the Starlin runs."
    },
    {
        slug: "rocket",
        name: "Rocket",
        file: "Rocket",
        role: "Strategist",
        hp: 250,
        affiliation: "Guardians",
        year: 1976,
        species: "Raccoon",
        ult: "C.Y.A.",
        abilities: ["BOMBARD MODE", "REPAIR MODE", "C.Y.A.", "JETPACK DASH", "B.R.B.", "WILD CRAWL", "FLYING ACE"],
        emoji: ["🔧", "😂", "🦝", "🔫"],
        origin: "Rocket Raccoon first appeared in <em>Marvel Preview</em> #7 in 1976, created by Bill Mantlo and Keith Giffen. The character was a comparatively minor cosmic-Marvel figure for thirty years before the 2008 <em>Annihilation</em> Guardians of the Galaxy reformation and the 2014 James Gunn film. Like Star-Lord, Rocket's modern profile is film-driven.",
        history: "Most of Rocket's defining material is the Abnett-Lanning Guardians run and the Skottie Young 2014 solo series. The cinematic version is the cultural touchstone for most readers, and the Rivals design leans into the brown-and-white fur with the Bombard Mode jetpack as a callback to his comic identity as a Halfworld constable.",
        rivals: "Rocket is a 250 HP Strategist whose kit is unusual for the role — he is the only Strategist whose primary identity is damage rather than healing. Bombard Mode is a high-DPS turret stance; Repair Mode is the healing toggle. The skill ceiling is in toggling between modes at the right moments. Players who lock into one mode underperform; players who flicker between them can both heal and contribute fight damage.",
        abilitiesNote: "Bombard Mode is the damage stance. Repair Mode is the healing stance. Jetpack Dash is the mobility. Flying Ace is the secondary mobility. C.Y.A., his ultimate, is a self-buff with high mobility and damage that lets him commit to a fight in a way Strategists typically cannot.",
        spotting: "Rocket's species cell is Raccoon, unique to him. His hair color array of Black, Brown, and White is the only triple-color entry in the database. His Red eye color is shared only with Ultron. In Pixelation Mode the brown-fur palette is distinctive. In Emoji Mode the raccoon is essentially literal."
    },
    {
        slug: "loki",
        name: "Loki",
        file: "Loki",
        role: "Strategist",
        hp: 275,
        affiliation: "Villain",
        year: 1949,
        species: "Asgardian",
        ult: "GOD OF MISCHIEF",
        abilities: ["MYSTICAL MISSILE", "GOD OF MISCHIEF", "REGENERATION DOMAIN", "DOPPELGANGER", "DEVIOUS EXCHANGE", "BACKSTAB", "DECEPTION"],
        emoji: ["🃏", "🟢", "👑", "🪄"],
        origin: "Loki Laufeyson first appeared in <em>Venus</em> #6 in August 1949 — a pre-Marvel Atlas Comics title with no continuity to the modern superhero universe. The Loki we recognize debuted in <em>Journey into Mystery</em> #85 in October 1962 alongside Thor, but the Rivaldle database tracks the 1949 first-appearance because that was the original publishing date for the character name.",
        history: "Walt Simonson's 1980s Thor run is the definitive Loki framing. Tom Hiddleston's portrayal in the MCU films and Disney+ series has reshaped the character's cultural form — most contemporary readers picture Hiddleston when they read Loki. The Kieron Gillen <em>Loki: Agent of Asgard</em> run from 2014 is the modern comic version of that anti-hero framing.",
        rivals: "Loki is a 275 HP Strategist whose kit is built around deception. Doppelganger creates duplicates of him that act as decoys. Devious Exchange swaps his position with a teammate. Backstab is a melee burst. The kit is the highest-skill-floor Strategist in the game; players who do not actively use Doppelganger and Devious Exchange play him as an underpowered Strategist, and players who do play him as a tier-defining one.",
        abilitiesNote: "Mystical Missile is the basic ranged. Regeneration Domain is the team heal. Doppelganger is the decoy. Devious Exchange is the swap. Backstab is the burst. Deception is the disguise — he can mimic an enemy hero. God of Mischief, his ultimate, conjures a chaos zone that triggers all his other abilities at once.",
        spotting: "Loki's gender cell is the only 'Fluid' entry in the database — a single-field fingerprint. The horned helmet is the silhouette tell, paired with Hela and Thor. The 1949 origin year is unique to him. Any one of those three fields resolves Classic Mode in one guess."
    },
    {
        slug: "luna-snow",
        name: "Luna Snow",
        file: "LunaSnow",
        role: "Strategist",
        hp: 275,
        affiliation: "Avengers",
        year: 2018,
        species: "Human",
        ult: "FATE OF BOTH WORLDS",
        abilities: ["LIGHT & DARK ICE", "FATE OF BOTH WORLDS", "ICE ARTS", "SHARE THE STAGE", "ABSOLUTE ZERO", "CRYO HEART", "SMOOTH SKATE"],
        emoji: ["❄️", "🎤", "✨", "🌙"],
        origin: "Seol Hee debuted in <em>Future Fight Firsts: Luna Snow</em> #1 in 2019, created by Alyssa Wong and Gang Hyuk Lim. Luna Snow originally appeared in the mobile game <em>Marvel Future Fight</em> in 2018 — making her one of the only Marvel characters whose first appearance was in a video game rather than in print. The 2018 date in our database tracks her digital debut.",
        history: "Luna Snow's published comic appearances are limited compared to most of the roster. Her primary cultural role is as a K-pop-coded Marvel hero — a deliberate Marvel Korea creation that has since been integrated into mainline Avengers and Future Avengers stories. Her presence in <em>Marvel Rivals</em> is one of the larger pieces of her comic-mainstream visibility.",
        rivals: "Luna Snow is a 275 HP Strategist whose kit is built around toggle-stance healing. Light Ice heals teammates; Dark Ice damages enemies. Share the Stage is a team-wide damage and movement buff. The skill ceiling is in stance switching during fights — players who commit to either heal or damage individually underperform compared to players who flicker between them based on team HP.",
        abilitiesNote: "Light & Dark Ice is the dual-stance primary. Ice Arts is the AoE option. Share the Stage is the team buff. Cryo Heart is the survivability tool. Smooth Skate is the mobility. Fate of Both Worlds, her ultimate, is a long-duration song that buffs allies and pressures enemies in range.",
        spotting: "Luna Snow's 2018 origin year is the most recent in the database — a single-field fingerprint. Her dual eye color (Blue and Brown) and dual hair color (Black and White) are also distinctive. The microphone in Emoji Mode is the strongest cue. In Pixelation Mode the white-and-pink palette is a tell."
    },
    {
        slug: "mantis",
        name: "Mantis",
        file: "Mantis",
        role: "Strategist",
        hp: 250,
        affiliation: "Guardians",
        year: 1973,
        species: "Empath",
        ult: "SOUL RESURGENCE",
        abilities: ["LIFE ENERGY BLAST", "SOUL RESURGENCE", "SPORE SLUMBER", "ALLIED INSPIRATION", "NATURAL ANGER", "HEALING FLOWER", "NATURE'S FAVOR", "NATURE'S SOUL"],
        emoji: ["🌸", "😌", "👾", "🌌"],
        origin: "Mantis first appeared in <em>Avengers</em> #112 in June 1973, created by Steve Englehart and Don Heck. She was conceived as the Celestial Madonna — a Vietnamese-German martial artist destined to give birth to the cosmic messiah. Marvel's most notable contribution-without-attribution since: she has appeared at DC under a different name due to a long contract dispute about who owned the character.",
        history: "Mantis' modern profile is overwhelmingly film-driven — Pom Klementieff's portrayal in the <em>Guardians of the Galaxy</em> films is what most contemporary readers picture. The Rivals design leans on the cinematic version: green skin, antennae, and the empathic touch as the central kit conceit.",
        rivals: "Mantis is a 250 HP Strategist whose kit is the most heal-dense in the role group. Healing Flower drops a sustained-heal flower; Allied Inspiration buffs nearby teammates. The skill ceiling is in flower placement — well-placed flowers can sustain a position for an extended team fight; poorly placed flowers waste the cooldown. She is the most forgiving Strategist for new players.",
        abilitiesNote: "Life Energy Blast is the damage option. Healing Flower is the deployable heal. Allied Inspiration is the team buff. Spore Slumber is the CC sleep. Nature's Favor is the burst heal. Soul Resurgence, her ultimate, ressurects fallen teammates and is one of the few abilities in the game that reverses team-fight outcomes.",
        spotting: "Mantis' species cell is Empath — unique in the database — a one-guess fingerprint in Classic Mode. The pink-and-green palette is unusual in Pixelation Mode. In Emoji Mode the cherry blossom is a deliberate cue toward her Vietnamese-German heritage rather than the more obvious mantis insect, which would have been too literal."
    },
    {
        slug: "cloak-and-dagger",
        name: "Cloak and Dagger",
        file: "CloakAndDagger",
        role: "Strategist",
        hp: 275,
        affiliation: "X-Men",
        year: 1982,
        species: "Mutant",
        ult: "ETERNAL BOND",
        abilities: ["DARKFORCE CLOAK", "ETERNAL BOND", "LIGHT'S EMBRACE", "TERROR CAPE", "DARK TELEPORTATION"],
        emoji: ["🌘", "🔗", "🗡️", "🌌"],
        origin: "Cloak and Dagger first appeared in <em>The Spectacular Spider-Man</em> #64 in March 1982, created by Bill Mantlo and Ed Hannigan. They were two runaway teenagers — Tyrone Johnson and Tandy Bowen — who had been experimented on with synthetic drugs and developed light-and-shadow powers as a result.",
        history: "Cloak and Dagger have always been a pair, which is unusual for Marvel character licensing. They have had two solo series in the 1980s, frequent X-Men crossovers, and a 2018 Freeform TV series. The <em>Marvel Rivals</em> design treats them as a single unit — the player swaps between Cloak's dark stance and Dagger's light stance dynamically.",
        rivals: "Cloak and Dagger is a 275 HP Strategist with the most unusual character switch mechanic in the role group. Cloak provides darkness-based mobility and disengage; Dagger provides light-based healing and damage. The kit rewards stance management — Dagger heals, Cloak escapes, and the swap window is the entire skill expression of the character.",
        abilitiesNote: "Darkforce Cloak is the Cloak-stance primary. Light's Embrace is the Dagger-stance heal. Terror Cape is the Cloak CC. Dark Teleportation is the disengage. Eternal Bond, the ultimate, links the two halves of the character together for a brief duration of empowered output.",
        spotting: "Cloak and Dagger's gender cell is 'Other' — unique in the database (alongside Loki's 'Fluid'). Their dual eye color (Grey and Blue) and dual hair color (Black and Blonde) are tied to the two-character framing. In Emoji Mode the moon-link pairing is our cue toward the duality. In Classic Mode the affiliation is X-Men, narrowing them within the X-Men cluster by their 1982 origin year."
    },
    {
        slug: "jeff-the-land-shark",
        name: "Jeff the Land Shark",
        file: "JeffTheLandShark",
        role: "Strategist",
        hp: 250,
        affiliation: "None",
        year: 2019,
        species: "Land Shark",
        ult: "IT'S JEFF!",
        abilities: ["JOYFUL SPLASH", "AQUA BURST", "IT'S JEFF!", "HIDE AND SEEK", "HEALING BUBBLE", "OBLIVIOUS CUTENESS"],
        emoji: ["🌊", "🐟", "🦈", "😂"],
        origin: "Jeff the Land Shark first appeared in <em>West Coast Avengers</em> #7 in March 2019, created by Kelly Thompson and Gurihiru. He is a small terrestrial shark adopted by Gwenpool, and his entire publishing existence is structured around the joke that he is the cutest character Marvel has ever published.",
        history: "Jeff has appeared primarily in <em>West Coast Avengers</em>, <em>Gwenpool Strikes Back</em>, and his own miniseries by Kelly Thompson. He is one of the youngest characters in the database and one of the most overtly comic-relief-coded heroes in <em>Marvel Rivals</em> — his entire kit is built around the joke that you are healing teammates by being adorable.",
        rivals: "Jeff the Land Shark is a 250 HP Strategist whose kit is built around mobility-based healing. Healing Bubble is the deployable heal. Joyful Splash is the AoE damage option. Hide and Seek is the survivability tool. The kit rewards aggressive forward play; he heals more by being in the front line than by being behind it.",
        abilitiesNote: "Joyful Splash is the damage tool. Aqua Burst is the burst alternative. Healing Bubble is the deployable. Hide and Seek is the disengage. Oblivious Cuteness is the buff. It's Jeff!, his ultimate, is the now-iconic move where he scoops up enemies and swallows them — high-skill, high-reward, and high-comedy.",
        spotting: "Jeff's species cell is 'Land Shark' — unique to him in the database, a one-guess fingerprint. His 2019 origin year is the most recent in the database tied with Luna Snow. The shark emoji in Emoji Mode is essentially literal. In Pixelation Mode the gray-and-blue palette is a tell."
    },
    {
        slug: "invisible-woman",
        name: "Invisible Woman",
        file: "InvisibleWoman",
        role: "Strategist",
        hp: 275,
        affiliation: "Fantastic 4",
        year: 1961,
        species: "Human",
        ult: "INVISIBLE BOUNDARY",
        abilities: ["ORB PROJECTION", "INVISIBLE BOUNDARY", "PSIONIC VORTEX", "FORCE PHYSICS", "AGILE STRIKE", "VEILED STEP", "GUARDIAN SHIELD", "COVert ADVANCE"],
        emoji: [" ", "🌫️", "🛡️", "💎"],
        origin: "Sue Storm first appeared in <em>The Fantastic Four</em> #1 in November 1961, created by Stan Lee and Jack Kirby. She was originally written as a comparatively passive team member; later writers, particularly John Byrne in the 1980s, reframed her as the most powerful member of the Fantastic Four — her force-field mastery scales much further than the team's other powers.",
        history: "Sue Storm's defining runs are John Byrne's 1980s Fantastic Four, Mark Waid's 2000s tenure, and Jonathan Hickman's 2010 reboot. Hickman's run in particular treats her as the Fantastic Four's most-feared combatant in cosmic-scale stories, and the Rivals design leans into that — her ultimate is a force-field zone that effectively walls off a portion of the map.",
        rivals: "Invisible Woman is a 275 HP Strategist whose kit is built around force fields and stealth. Veiled Step is the invisibility ability. Guardian Shield is the deployable barrier. The kit rewards positioning over reflexes — well-placed shields and stealthed flanks define her impact, not damage output. She is the Strategist with the highest skill ceiling for spatial awareness.",
        abilitiesNote: "Orb Projection is the basic damage. Psionic Vortex is the area control. Force Physics is the manipulation. Guardian Shield is the deployable barrier. Veiled Step is the stealth. Invisible Boundary, her ultimate, drops a massive force-field zone that contains everyone inside.",
        spotting: "Invisible Woman is the only Marvel Rivals character whose first emoji slot is a space character — that single quirk in the Emoji Mode database is a fingerprint. Her Fantastic 4 affiliation narrows her to four heroes; her Strategist role pins her down within that group instantly. In Pixelation Mode the blue-and-white costume is similar to Mister Fantastic, which makes it the harder of the two to read."
    },
    {
        slug: "ultron",
        name: "Ultron",
        file: "Ultron",
        role: "Strategist",
        hp: 250,
        affiliation: "None",
        year: 1968,
        species: "Robot",
        ult: "RAGE OF ULTRON",
        abilities: ["ENCEPHALO-RAY", "RAGE OF ULTRON", "IMPERATIVE: FIREWALL", "IMPERATIVE: PATCH", "DYNAMIC FLIGHT", "NANO RAY"],
        emoji: ["🤖", "🧠", "⚙️", "☠️"],
        origin: "Ultron first appeared (as the Crimson Cowl) in <em>Avengers</em> #54 in 1968, created by Roy Thomas and John Buscema, with the full Ultron reveal in <em>Avengers</em> #55 the following month. The character was designed as Hank Pym's robotic 'son' — an artificial intelligence that turned on its creator — and the relationship has been the load-bearing element of every major Ultron story since.",
        history: "Ultron's most-cited modern stories are Kurt Busiek's <em>Annual</em>-ending <em>Ultron Unlimited</em> arc in 1999 and Brian Bendis' <em>Age of Ultron</em> event in 2013. The 2015 film <em>Avengers: Age of Ultron</em> brought the character to a mass audience. The Rivals version is unusual in casting him as a Strategist — most depictions frame Ultron as a damage dealer or boss-tier antagonist.",
        rivals: "Ultron is a 250 HP Strategist whose kit is built around drone-style support. Imperative: Patch is the heal — a self-replicating nano-repair signature. Imperative: Firewall is the team shield. Dynamic Flight is the mobility, which makes him the only flying Strategist in the game. The skill ceiling is in altitude management; he heals from above, which gives him a different sightline than ground-locked Strategists.",
        abilitiesNote: "Encephalo-Ray is the basic damage. Nano Ray is the AOE alternative. Imperative: Patch is the heal. Imperative: Firewall is the team shield. Dynamic Flight is the mobility. Rage of Ultron, his ultimate, is the alpha-strike — a sustained beam of nano-damage that punishes clustered enemies.",
        spotting: "Ultron's species cell is Robot — unique to him in the database. His Red eye color is shared only with Rocket. His Orange-and-Red eye color array is unique. Any one of those three fields is a Classic Mode fingerprint. In Pixelation Mode the silver-and-purple palette is distinctive. In Emoji Mode the robot is essentially literal."
    }
];
